version: "3.9"

services:
  db:
    image: postgres:16
    container_name: auth-db
    restart: always
    environment:
      POSTGRES_DB: passmais
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  authservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-service
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/passmais
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_OPEN_IN_VIEW: false
      JWT_SECRET: p$ssm41s-@uth-k3y-2025
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
